
import dao.ConnectionProvider;
import javax.swing.JOptionPane;
import java.sql.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author baste
 */
public class AddThuoc extends javax.swing.JFrame {
    
    private String numberPattern = "^[0-9]*$";
    /**
     * Creates new form AddThuoc
     */
    public AddThuoc() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtUniqueid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTenthuoc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTenNSX = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSoluong = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtGia = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Thêm thuốc");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 25, 212, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 79, 850, 10));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, 38, 36));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("ID Thuốc");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 107, 147, -1));

        txtUniqueid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtUniqueid, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 139, 300, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Tên thuốc");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 187, 125, -1));

        txtTenthuoc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtTenthuoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 219, 300, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Tên nhà sản xuất");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 268, 191, -1));

        txtTenNSX.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtTenNSX, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 300, 300, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Số lượng");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 348, 64, -1));

        txtSoluong.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtSoluong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoluongActionPerformed(evt);
            }
        });
        getContentPane().add(txtSoluong, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 380, 300, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Giá mỗi đơn vị");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 107, 100, -1));

        txtGia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 139, 300, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        jButton2.setText("Lưu");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 219, 150, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/all_pages_background.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Đóng cửa sổ thêm thuốc ?", "Chọn", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            setVisible(false);
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtSoluongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoluongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoluongActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String uniqueId = txtUniqueid.getText();
        String tenThuoc = txtTenthuoc.getText();
        String tenNSX = txtTenNSX.getText();
        String soLuong = txtSoluong.getText();
        String gia = txtGia.getText();
        
        
        if (uniqueId.equals("")) {
            JOptionPane.showMessageDialog(null, "Thuốc Id không được trống!");
        }else if (tenThuoc.equals("")){
            JOptionPane.showMessageDialog(null, "Tên thuốc không được trống!");
        }else if (tenNSX.equals("")){
            JOptionPane.showMessageDialog(null, "Tên NSX không được trống!");
        }
        else if (soLuong.equals("")){
            JOptionPane.showMessageDialog(null, "Số lượng không được trống!");
        }else if (!soLuong.matches(numberPattern)){
            JOptionPane.showMessageDialog(null, "Số lượng không hợp lệ!");
        }else if (gia.equals("")){
            JOptionPane.showMessageDialog(null, "Giá không được trống!");
        }else if (!gia.matches(numberPattern)){
            JOptionPane.showMessageDialog(null, "Giá không hợp lệ!");
        }
        else{
            try {
                Connection conn = ConnectionProvider.getConnection();
                PreparedStatement ps = conn.prepareStatement("INSERT INTO thuoc (uniqueId,tenThuoc,tenNSX,soLuong,gia) VALUES (?,?,?,?,?)");
                
                ps.setString(1, uniqueId);
                ps.setString(2, tenThuoc);
                ps.setString(3, tenNSX);
                ps.setString(4, soLuong);
                ps.setString(5, gia);
                
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Thêm thuốc thành công!");
                setVisible(false);
                new AddThuoc().setVisible(true);
            
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddThuoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddThuoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddThuoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddThuoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddThuoc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtSoluong;
    private javax.swing.JTextField txtTenNSX;
    private javax.swing.JTextField txtTenthuoc;
    private javax.swing.JTextField txtUniqueid;
    // End of variables declaration//GEN-END:variables
}
